from framework.locators.login_page_locators import LoginPageLocators
from framework.locators.popup_modal_locators import PopupModalLocators
from framework.locators.home_page_locators import HomePageLocators
